# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from com_arm/Calib_camera.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Calib_camera(genpy.Message):
  _md5sum = "08b01bb680791f8362dea80ccacc5fb0"
  _type = "com_arm/Calib_camera"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool point0
bool point1
bool point2
bool point3
"""
  __slots__ = ['point0','point1','point2','point3']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       point0,point1,point2,point3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Calib_camera, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.point0 is None:
        self.point0 = False
      if self.point1 is None:
        self.point1 = False
      if self.point2 is None:
        self.point2 = False
      if self.point3 is None:
        self.point3 = False
    else:
      self.point0 = False
      self.point1 = False
      self.point2 = False
      self.point3 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.point0, _x.point1, _x.point2, _x.point3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.point0, _x.point1, _x.point2, _x.point3,) = _get_struct_4B().unpack(str[start:end])
      self.point0 = bool(self.point0)
      self.point1 = bool(self.point1)
      self.point2 = bool(self.point2)
      self.point3 = bool(self.point3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.point0, _x.point1, _x.point2, _x.point3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.point0, _x.point1, _x.point2, _x.point3,) = _get_struct_4B().unpack(str[start:end])
      self.point0 = bool(self.point0)
      self.point1 = bool(self.point1)
      self.point2 = bool(self.point2)
      self.point3 = bool(self.point3)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
