(cl:in-package com_arm-msg)
(cl:export '(ST1-VAL
          ST1
          ST2-VAL
          ST2
          ST3-VAL
          ST3
          ST4-VAL
          ST4
          ST5-VAL
          ST5
          ST20-VAL
          ST20
          ST21-VAL
          ST21
          ST22-VAL
          ST22
          ST23-VAL
          ST23
          ST24-VAL
          ST24
          R1D-VAL
          R1D
          R2D-VAL
          R2D
          R11D-VAL
          R11D
          R12D-VAL
          R12D
          R1G-VAL
          R1G
          R2G-VAL
          R2G
          R11G-VAL
          R11G
          R12G-VAL
          R12G
          PI1-VAL
          PI1
          PI2-VAL
          PI2
          PI7-VAL
          PI7
          PI8-VAL
          PI8
          D1-VAL
          D1
          D2-VAL
          D2
          D11-VAL
          D11
          D12-VAL
          D12
          V1-VAL
          V1
          V2-VAL
          V2
          V11-VAL
          V11
          V12-VAL
          V12
          PS1-VAL
          PS1
          PS2-VAL
          PS2
          PS3-VAL
          PS3
          PS4-VAL
          PS4
          PS5-VAL
          PS5
          PS20-VAL
          PS20
          PS21-VAL
          PS21
          PS22-VAL
          PS22
          PS23-VAL
          PS23
          PS24-VAL
          PS24
          D1D-VAL
          D1D
          D2D-VAL
          D2D
          D11D-VAL
          D11D
          D12D-VAL
          D12D
          D1G-VAL
          D1G
          D2G-VAL
          D2G
          D11G-VAL
          D11G
          D12G-VAL
          D12G
          CPI1-VAL
          CPI1
          CPI2-VAL
          CPI2
          CPI7-VAL
          CPI7
          CPI8-VAL
          CPI8
          CP1-VAL
          CP1
          CP2-VAL
          CP2
          CP9-VAL
          CP9
          CP10-VAL
          CP10
))